name: Build Dev Version

on:
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build with Release
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: x86_64-unknown-linux-gnu
        override: true
    
    - name: Compile project
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target=x86_64-unknown-linux-gnu
    
    - name: Check out repository
      uses: actions/upload-artifact@v3.1.2
      with:
        name: dev-deploy-executable
        path: target/x86_64-unknown-linux-gnu/release/improved-eureka
